name: Log Time Job
on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 5 minutes

permissions: 
 contents: write
 
jobs:
  log_time:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run logging script
      run: |
        chmod +x log_time.sh
        ./log_time.sh

    - name: Commit and push changes
      run: |
        git config --global user.name "jhoen"
        git config --global user.email "jhoen.alban@github.com"
        git add log.txt
        git commit -m "Update log file with new timestamp" || echo "No changes to
        commit"
        git push
